# ref: https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows

name: Deploy PyPI package

on:
  push:
    branches:
      - main
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:

  # production build
  build:
    name: Create package üì¶
    runs-on: ubuntu-latest

    steps:

    - name: Checkout source
      uses: actions/checkout@v4
      with:
        fetch-tags: true
        fetch-depth: 0

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - name: Build library
      run: python3 -m pip install build --user

    - name: Build wheel and tarball
      run: python3 -m build

    - name: Save package
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/


  # This will be triggered only when a tag is pushed
  publish-to-pypi:
    name: Publish to PyPI üêç (pypi.org)
    if: startsWith(github.ref, 'refs/tags/')
    needs:
    - build
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/stock-indicators

    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:

    - name: Download package
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

    - name: Publish package üì¶ to pypi.org
      uses: pypa/gh-action-pypi-publish@release/v1


  # This will be triggered everytime when commit is pushed on main branch
  publish-to-testpypi:
    name: Publish to PyPI üêç (test.pypi.org)
    needs:
    - build
    runs-on: ubuntu-latest

    environment:
      name: pypi-test
      url: https://test.pypi.org/p/stock-indicators

    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:

    - name: Download package
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

    - name: Publish package üì¶ to test.pypi.org
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
